package com.monitor.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.monitor.greendao.LocationEntity;
import com.monitor.greendao.SmsEntity;
import com.monitor.greendao.MediaEntity;
import com.monitor.greendao.LogEntity;

import com.monitor.greendao.LocationEntityDao;
import com.monitor.greendao.SmsEntityDao;
import com.monitor.greendao.MediaEntityDao;
import com.monitor.greendao.LogEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationEntityDaoConfig;
    private final DaoConfig smsEntityDaoConfig;
    private final DaoConfig mediaEntityDaoConfig;
    private final DaoConfig logEntityDaoConfig;

    private final LocationEntityDao locationEntityDao;
    private final SmsEntityDao smsEntityDao;
    private final MediaEntityDao mediaEntityDao;
    private final LogEntityDao logEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationEntityDaoConfig = daoConfigMap.get(LocationEntityDao.class).clone();
        locationEntityDaoConfig.initIdentityScope(type);

        smsEntityDaoConfig = daoConfigMap.get(SmsEntityDao.class).clone();
        smsEntityDaoConfig.initIdentityScope(type);

        mediaEntityDaoConfig = daoConfigMap.get(MediaEntityDao.class).clone();
        mediaEntityDaoConfig.initIdentityScope(type);

        logEntityDaoConfig = daoConfigMap.get(LogEntityDao.class).clone();
        logEntityDaoConfig.initIdentityScope(type);

        locationEntityDao = new LocationEntityDao(locationEntityDaoConfig, this);
        smsEntityDao = new SmsEntityDao(smsEntityDaoConfig, this);
        mediaEntityDao = new MediaEntityDao(mediaEntityDaoConfig, this);
        logEntityDao = new LogEntityDao(logEntityDaoConfig, this);

        registerDao(LocationEntity.class, locationEntityDao);
        registerDao(SmsEntity.class, smsEntityDao);
        registerDao(MediaEntity.class, mediaEntityDao);
        registerDao(LogEntity.class, logEntityDao);
    }
    
    public void clear() {
        locationEntityDaoConfig.getIdentityScope().clear();
        smsEntityDaoConfig.getIdentityScope().clear();
        mediaEntityDaoConfig.getIdentityScope().clear();
        logEntityDaoConfig.getIdentityScope().clear();
    }

    public LocationEntityDao getLocationEntityDao() {
        return locationEntityDao;
    }

    public SmsEntityDao getSmsEntityDao() {
        return smsEntityDao;
    }

    public MediaEntityDao getMediaEntityDao() {
        return mediaEntityDao;
    }

    public LogEntityDao getLogEntityDao() {
        return logEntityDao;
    }

}
