package com.monitor.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOCATION_ENTITY".
 */
public class LocationEntity {

    private Long time;
    private double latitude;
    private double longitude;
    private String desc;

    public LocationEntity() {
    }

    public LocationEntity(Long time) {
        this.time = time;
    }

    public LocationEntity(Long time, double latitude, double longitude, String desc) {
        this.time = time;
        this.latitude = latitude;
        this.longitude = longitude;
        this.desc = desc;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

}
